version: '3'
services:
  mysql-db:
    image: mysql:latest
    container_name: kaddem-db
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=devops_project_db
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
    networks:
      - my-network
  spring-boot-app:
    image: yassinenajar/kaddem
    container_name: kaddem
    ports:
      - "8087:8089"
    restart: unless-stopped
    depends_on:
      - mysql-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://kaddem-db:3306/dbyassine?&createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
    networks:
      - my-network
networks:
  my-network:      